# Generated by Django 3.2.25 on 2024-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bespoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gift_recipient', models.CharField(choices=[('', 'Is this a gift for yourself or someone else? *'), ('1', 'Myself'), ('2', 'Someone else')], default='Is this a gift for yourself or someone else?*', max_length=30)),
                ('occasion', models.CharField(choices=[('', 'What sort of occasion is the collage for?*'), ('Birthday', 'Birthday'), ('Significant Milestone', 'Significant Milestone'), ('New Home', 'New Home'), ('Anniversary', 'Anniversary'), ('Wedding', 'Wedding'), ('Retirement', 'Retirement'), ('Not sure', 'Not sure'), ('Other', 'Other - details in comments below')], default='What sort of occasion is the collage for?*', max_length=30)),
                ('wishes', models.CharField(choices=[('', 'How many wishes would you like (all 30 x 30cm)?*'), ('1', '1'), ('4', '4'), ('6', '6'), ('9', '9')], default='How many wishes would you like (all 30 x 30cm)?*', max_length=40)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bespoke Collages',
            },
        ),
    ]
